name: cariddi
summary: Fast web crawler and scanner
description: |
      Take a list of domains, crawl urls and scan for endpoints, secrets, api keys, file extensions, tokens and more
version: 1.3.5
grade: stable
base: core20

confinement: strict

apps:
  cariddi:
    command: bin/cariddi
    plugs:
      - home
      - network

parts:
  cariddi:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/cariddi
